"""course ownership model

Revision ID: 4c98bfd6f37e
Revises: a8771ff7d535
Create Date: 2026-07-31 15:47:28.839256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c98bfd6f37e'
down_revision: Union[str, Sequence[str], None] = 'a8771ff7d535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Note: the autogenerated `ALTER COLUMN users.password_hash SET NOT NULL`
    was stripped here -- same SQLite reflection false-positive seen in the
    two prior migrations, not an actual model change.
    """
    op.add_column('courses', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_courses_owner_id'), 'courses', ['owner_id'], unique=False)

    # Best-effort backfill for pre-ownership-model courses: while `user_courses`
    # still exists, assign each course to its lowest-user_id enrollee. Courses
    # with no enrollment stay ownerless (still admin-manageable).
    op.execute(
        """
        UPDATE courses
        SET owner_id = (
            SELECT user_id FROM user_courses
            WHERE user_courses.course_id = courses.id
            ORDER BY user_courses.user_id
            LIMIT 1
        )
        WHERE EXISTS (SELECT 1 FROM user_courses WHERE user_courses.course_id = courses.id)
        """
    )

    op.drop_index(op.f('ix_user_courses_course_id'), table_name='user_courses')
    op.drop_index(op.f('ix_user_courses_id'), table_name='user_courses')
    op.drop_index(op.f('ix_user_courses_user_id'), table_name='user_courses')
    op.drop_table('user_courses')
    op.drop_column('courses', 'status')


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('courses', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'"), nullable=False))
    op.create_table('user_courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('uq_user_course'))
    )
    op.create_index(op.f('ix_user_courses_user_id'), 'user_courses', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_courses_id'), 'user_courses', ['id'], unique=False)
    op.create_index(op.f('ix_user_courses_course_id'), 'user_courses', ['course_id'], unique=False)
    op.drop_index(op.f('ix_courses_owner_id'), table_name='courses')
    op.drop_column('courses', 'owner_id')
