"""add foreign key constraints

Revision ID: a61b25bcaf56
Revises: aacfdec350b5
Create Date: 2026-07-31 22:22:50.529305

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a61b25bcaf56'
down_revision: Union[str, Sequence[str], None] = 'aacfdec350b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Note: the autogenerated `ALTER COLUMN users.password_hash SET NOT NULL`
    was stripped here -- same recurring SQLite reflection false-positive
    seen in every prior migration, not an actual model change.

    Constraints are explicitly named (autogenerate emitted `None` for the
    name, letting SQLAlchemy pick one) -- SQLite's batch mode, which
    recreates the whole table to add a constraint, requires a name upfront
    rather than deferring to naming-convention inference like a normal
    ALTER TABLE would.
    """
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_chat_history_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(
            'fk_chat_history_course_id_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('course_topics', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_course_topics_course_id_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_courses_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_documents_course_id_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_foreign_key('fk_documents_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_quiz_results_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(
            'fk_quiz_results_course_id_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_quiz_sessions_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(
            'fk_quiz_sessions_course_id_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE'
        )

    with op.batch_alter_table('weak_topics', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_weak_topics_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(
            'fk_weak_topics_course_id_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('weak_topics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_weak_topics_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_weak_topics_course_id_courses', type_='foreignkey')

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_sessions_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_quiz_sessions_course_id_courses', type_='foreignkey')

    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_results_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_quiz_results_course_id_courses', type_='foreignkey')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_course_id_courses', type_='foreignkey')
        batch_op.drop_constraint('fk_documents_user_id_users', type_='foreignkey')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_owner_id_users', type_='foreignkey')

    with op.batch_alter_table('course_topics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_topics_course_id_courses', type_='foreignkey')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_history_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_history_course_id_courses', type_='foreignkey')

    # ### end Alembic commands ###
