"""drop unused recommendation_histories and user_profiles tables

Revision ID: aacfdec350b5
Revises: ab9597ca20ba
Create Date: 2026-07-31 22:17:32.802905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacfdec350b5'
down_revision: Union[str, Sequence[str], None] = 'ab9597ca20ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Note: the autogenerated `ALTER COLUMN users.password_hash SET NOT NULL`
    was stripped here -- same recurring SQLite reflection false-positive
    seen in every prior migration, not an actual model change.

    Both tables were defined but never read from or written to anywhere in
    the app (recommendation_histories: superseded by dynamic, LLM-generated
    recommendations in backend/services/recommendation.py, which were never
    persisted here in the first place; user_profiles: fully unused, its
    fields duplicate users.level and weak_topics).
    """
    op.drop_index(op.f('ix_user_profiles_course_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_recommendation_histories_course_id'), table_name='recommendation_histories')
    op.drop_index(op.f('ix_recommendation_histories_id'), table_name='recommendation_histories')
    op.drop_index(op.f('ix_recommendation_histories_topic'), table_name='recommendation_histories')
    op.drop_index(op.f('ix_recommendation_histories_user_id'), table_name='recommendation_histories')
    op.drop_table('recommendation_histories')


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table('recommendation_histories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(), nullable=False),
    sa.Column('recommendation_text', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_histories_user_id'), 'recommendation_histories', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendation_histories_topic'), 'recommendation_histories', ['topic'], unique=False)
    op.create_index(op.f('ix_recommendation_histories_id'), 'recommendation_histories', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_histories_course_id'), 'recommendation_histories', ['course_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('learning_level', sa.VARCHAR(), nullable=False),
    sa.Column('recent_questions', sa.INTEGER(), nullable=False),
    sa.Column('weak_topics', sa.VARCHAR(), nullable=False),
    sa.Column('quiz_average', sa.FLOAT(), nullable=False),
    sa.Column('learning_frequency', sa.FLOAT(), nullable=False),
    sa.Column('last_active', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_course_id'), 'user_profiles', ['course_id'], unique=False)
    # ### end Alembic commands ###
