"""add course_topics table

Revision ID: ab9597ca20ba
Revises: 4c98bfd6f37e
Create Date: 2026-07-31 20:56:24.821356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9597ca20ba'
down_revision: Union[str, Sequence[str], None] = '4c98bfd6f37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Note: the autogenerated `ALTER COLUMN users.password_hash SET NOT NULL`
    was stripped here -- same recurring SQLite reflection false-positive
    seen in every prior migration, not an actual model change.
    """
    op.create_table('course_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_topics_course_id'), 'course_topics', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_topics_id'), 'course_topics', ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_course_topics_id'), table_name='course_topics')
    op.drop_index(op.f('ix_course_topics_course_id'), table_name='course_topics')
    op.drop_table('course_topics')
